import { clone, createInitialState, requireLiteralAction } from '../domain/contracts.js';
import { R3_TURN_LEASE_MS } from './job-policy.js';

export const R3_ATTEMPT_FENCE_CONFLICT = 'r3_attempt_fence_conflict';
export function createInMemoryR3Persistence() { return { games: new Map(), states: new Map(), jobs: new Map(), turns: new Map() }; }
function id() { return globalThis.crypto?.randomUUID?.() ?? `r3-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function fence() { const error = new Error(R3_ATTEMPT_FENCE_CONFLICT); error.code = R3_ATTEMPT_FENCE_CONFLICT; return error; }
function assertAttempt(job, attempt) { if (!job || job.status === 'committed' || job.status === 'failed' || job.action_id !== attempt.actionId || job.attempt_no !== attempt.attemptNo) throw fence(); }

export class InMemoryR3Store {
  constructor({ contentVersion = 'company-r3-m0', clock = () => Date.now(), persistence = createInMemoryR3Persistence() } = {}) { this.contentVersion = contentVersion; this.clock = clock; Object.assign(this, persistence); }
  now() { return new Date(this.clock()).toISOString(); }
  createGame({ profile, locationId = null, presentActorIds = [] }) { const gameId = id(); const created = this.now(); this.games.set(gameId, { game_id: gameId, content_version: this.contentVersion, profile: clone(profile), created_at: created }); this.states.set(gameId, { game_id: gameId, revision: 0, committed_turn: 0, state: createInitialState(profile, locationId, presentActorIds), updated_at: created }); return this.context(gameId); }
  createOpening(gameId, payload) { if (!this.games.has(gameId)) throw new Error('r3_game_not_found'); const key = `${gameId}:0`; if (!this.turns.has(key)) { const current = this.states.get(gameId); const stateAfter = clone(payload.stateAfter ?? current.state); this.states.set(gameId, { ...current, state: stateAfter, updated_at: this.now() }); this.turns.set(key, { game_id: gameId, turn_number: 0, revision: 0, literal_action: '', story_text: payload.storyText, choices: [...(payload.choices ?? [])], turn_summary: payload.summary, mind_monitor: clone(payload.mindMonitor ?? {}), observer_raw: clone(payload.observerRaw ?? {}), observer_applied: clone(payload.observerApplied ?? {}), warnings: [...(payload.warnings ?? [])], state_after: stateAfter, committed_at: this.now() }); } return this.context(gameId); }
  context(gameId) { if (!this.games.has(gameId)) throw new Error('r3_game_not_found'); const state = this.states.get(gameId); const turns = [...this.turns.values()].filter(turn => turn.game_id === gameId).sort((a, b) => a.turn_number - b.turn_number); this.expireStaleJob(gameId, state.committed_turn + 1); const job = [...this.jobs.values()].find(item => item.game_id === gameId && item.turn_number === state.committed_turn + 1) ?? null; return { game: clone(this.games.get(gameId)), state: clone(state), turns: clone(turns), job: job ? clone(job) : null }; }
  getJob(gameId, turnNumber) { this.expireStaleJob(gameId, turnNumber); return clone(this.jobs.get(`${gameId}:${turnNumber}`) ?? null); }
  reserveTurn({ gameId, turnNumber, actionId, literalAction, retryFailed = false }) { requireLiteralAction(literalAction); if (!this.games.has(gameId)) throw new Error('r3_game_not_found'); const state = this.states.get(gameId); if (!state || state.committed_turn + 1 !== turnNumber) throw new Error('r3_turn_conflict'); this.expireStaleJob(gameId, turnNumber); const key = `${gameId}:${turnNumber}`; const existing = this.jobs.get(key); if (existing) { if (existing.status === 'failed' && retryFailed) { Object.assign(existing, { action_id: actionId, literal_action: literalAction, status: 'reserved', stage: 'reserved', story_text: '', error_code: null, attempt_no: existing.attempt_no + 1, updated_at: this.now() }); return { job: clone(existing), created: true, retried: true }; } return { job: clone(existing), created: false }; } const now = this.now(); const job = { game_id: gameId, turn_number: turnNumber, action_id: actionId, literal_action: literalAction, status: 'processing', stage: 'reserved', story_text: '', error_code: null, attempt_no: 1, progress_writes: 0, created_at: now, updated_at: now }; this.jobs.set(key, job); return { job: clone(job), created: true }; }
  updateProgress({ gameId, turnNumber, attempt, storyText }) { const job = this.jobs.get(`${gameId}:${turnNumber}`); assertAttempt(job, attempt); job.story_text = storyText; job.stage = 'story_streaming'; job.progress_writes = (job.progress_writes ?? 0) + 1; job.updated_at = this.now(); return clone(job); }
  markStoryComplete({ gameId, turnNumber, attempt, storyText }) { const job = this.jobs.get(`${gameId}:${turnNumber}`); assertAttempt(job, attempt); job.story_text = storyText; job.stage = 'story_complete'; job.updated_at = this.now(); return clone(job); }
  commitTurn({ gameId, turnNumber, attempt, expectedRevision, storyText, choices, summary, mindMonitor, observerRaw, observerApplied, warnings, stateAfter }) { const state = this.states.get(gameId); const job = this.jobs.get(`${gameId}:${turnNumber}`); if (!state || state.revision !== expectedRevision || state.committed_turn + 1 !== turnNumber) throw new Error('r3_commit_conflict'); assertAttempt(job, attempt); const committedAt = this.now(); const nextRevision = state.revision + 1; this.states.set(gameId, { ...state, revision: nextRevision, committed_turn: turnNumber, state: clone(stateAfter), updated_at: committedAt }); this.turns.set(`${gameId}:${turnNumber}`, { game_id: gameId, turn_number: turnNumber, revision: 1, literal_action: attempt.literalAction, story_text: storyText, choices: [...(choices ?? [])], turn_summary: summary, mind_monitor: clone(mindMonitor ?? {}), observer_raw: clone(observerRaw ?? {}), observer_applied: clone(observerApplied ?? {}), warnings: [...(warnings ?? [])], state_after: clone(stateAfter), committed_at: committedAt }); Object.assign(job, { status: 'committed', stage: 'committed', story_text: storyText, updated_at: committedAt }); return this.context(gameId); }
  failJob({ gameId, turnNumber, attempt, errorCode }) { const job = this.jobs.get(`${gameId}:${turnNumber}`); assertAttempt(job, attempt); Object.assign(job, { status: 'failed', stage: 'failed', error_code: errorCode || 'r3_turn_failed', updated_at: this.now() }); return this.context(gameId); }
  expireStaleJob(gameId, turnNumber) { const job = this.jobs.get(`${gameId}:${turnNumber}`); if (job?.status === 'processing' && this.clock() - Date.parse(job.updated_at) >= R3_TURN_LEASE_MS) { Object.assign(job, { status: 'failed', stage: 'failed', error_code: 'r3_stale_turn_timeout', updated_at: this.now() }); return true; } return false; }
}
